---
- name: create a group and a user
  hosts: all
  become: yes

  tasks: 
  - name: create a group
    group:
      name: mygroup
      state: present

  - name: create a user
    user: name=akash password=root group=mygroup shell=/bin/bash
