#SPDX-License-Identifier: MIT-0
---
# handlers file for ansible
- name: enable apache2
  service:
    name: "{{ package }}"
    enabled: yes

- name: enable httpd
  service:
    name: "{{ red }}"
    enabled: yes
