#SPDX-License-Identifier: MIT-0
---
# tasks file for ansible
  - name: install apache2
    when: ansible_os_family in ["Debian","Ubuntu"]
    apt:
      update_cache: yes
      name: "{{ package }}"
      state: present
    notify:
    - enable apache2

  - name: install httpd
    when: ansible_os_family in ["Redhat","RHEL"]
    yum:
      update_cache: yes
      name: "{{ red }}"
      state: present
    notify:
    - enable httpd
